package com.lifebook.Lifebook.dagger.modules;

import com.lifebook.Lifebook.model.UnifiedEntity;
import dagger.Module;
import dagger.Provides;
import software.amazon.awssdk.enhanced.dynamodb.DynamoDbEnhancedClient;
import software.amazon.awssdk.enhanced.dynamodb.DynamoDbTable;
import software.amazon.awssdk.enhanced.dynamodb.TableSchema;
import software.amazon.awssdk.enhanced.dynamodb.extensions.AutoGeneratedTimestampRecordExtension;
import software.amazon.awssdk.regions.Region;
import software.amazon.awssdk.services.dynamodb.DynamoDbClient;

import javax.inject.Singleton;

@Module
public class DynamoDBConfig {
    private static final String LIFE_ENTITIES_TABLE = "LifeEntity";

    @Provides
    @Singleton
    public static DynamoDbEnhancedClient createEnhancedClient() {
        // Create a DynamoDB client
        DynamoDbClient dynamoDbClient = DynamoDbClient.builder()
            .region(Region.AP_SOUTH_1)
            .build();

        AutoGeneratedTimestampRecordExtension
            autoGeneratedTimestampRecordExtension = AutoGeneratedTimestampRecordExtension
            .create();

        return DynamoDbEnhancedClient
            .builder()
            .dynamoDbClient(dynamoDbClient)
            .extensions(autoGeneratedTimestampRecordExtension)
            .build();
    }

    @Provides
    @Singleton
    public static DynamoDbTable<UnifiedEntity> createTable(DynamoDbEnhancedClient enhancedClient){
        return enhancedClient
            .table(LIFE_ENTITIES_TABLE, TableSchema.fromBean(UnifiedEntity.class));
    }
}