package com.lifebook.Lifebook.configuration;

import org.springframework.context.annotation.Configuration;
import software.amazon.awssdk.enhanced.dynamodb.DynamoDbEnhancedClient;
import software.amazon.awssdk.enhanced.dynamodb.extensions.AutoGeneratedTimestampRecordExtension;
import software.amazon.awssdk.regions.Region;
import software.amazon.awssdk.services.dynamodb.DynamoDbClient;

@Configuration
public class DynamoDBConfig {

    public static DynamoDbEnhancedClient createEnhancedClient() {
        // Create a DynamoDB client
        DynamoDbClient dynamoDbClient = DynamoDbClient.builder()
            .region(Region.AP_SOUTH_1)
            .build();

        AutoGeneratedTimestampRecordExtension
            autoGeneratedTimestampRecordExtension = AutoGeneratedTimestampRecordExtension
            .create();

        return DynamoDbEnhancedClient
            .builder()
            .dynamoDbClient(dynamoDbClient)
            .extensions(autoGeneratedTimestampRecordExtension)
            .build();
    }
}